
stages:          
  - test
  - builddocker


run-test-job:   
  image: node:20   
  stage: test
  script:
    - npm install
    - npm run build
build-docker-image:   
  stage: builddocker
  needs: 
    - run-test-job   
  script:
    - docker build -t js--react-app
before_script:
  - npm install
  - chmod +x node_modules/.bin/vite

