
stages:          
  - test
  - builddocker

run-test-job:      
  image: node:20
  stage: test
  script:
    - npm run build
  before_script:
  - npm install
  - chmod +x node_modules/.bin/vite


build-docker-image:  
  image: docker:latest 
  stage: builddocker
  tags:
    - shell
  services:
    - docker:20-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  needs: 
    - run-test-job   
  script:
    - docker build -t js--react-app .

