version: "3.9"

services:
  koatag-fontend:
    build:
      context: ../../
      dockerfile: devops/dockerfiles/Dockerfile 
    container_name: koatag_fontend
    volumes:
      - ../../:/app
      - /app/node_modules
    ports:
      - "3000:80"
    restart: always
    networks:
      koatag_koaTag-network:
        ipv4_address: 172.24.1.5
networks:
  koatag_koaTag-network:
    external: true
# networks:
#   koaTag-network:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.24.0.0/16
